title =  "IT与法务"
languageCode = "zh_CN"
baseurl = "http://itlaws.cn/"
theme =  "next"
MetaDataFormat =  "toml"
canonifyurls =  true
builddrafts =  false
PaginatePath =  "p"
Paginate = 8
disablePathToLower =  false
hasCJKLanguage = true
preserveTaxonomyNames = false
uglyurls = false
pygmentsStyle = "monokai"
pygmentsUseClasses = true

[Params]
  Introduce = "IT & Laws"
  Description = "生命不息，折腾不止"
  Keywords =  "Choicky,深圳律师,IT与法务,生活印记,专利,商标,刑事,走私,盗窃,民事,合同纠纷"
  Subtitle = "把握当下，展望未来"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  BaiduStatsId = "3810cda5a4d6eec6d00cedd4521a7fb1"
  Fancybox = true

[Author]
  Name = "Choicky, 深圳律师"

[Params.Share]
  #DuoShuo = "itlaws"
  Baidu = true

[Params.Strings]
  Search = "搜索"
  Categories = "分类"
  Archive = "归档"
  Tags = "标签"
  Rss = "RSS 订阅"
  Toc = "文章目录"
  SiteInfo = "站点概览"
  Links = "友情链接"
  Blog = "博文"

[[Menu.Main]]
  Name = "首页"
  URL = "/"
  Weight = 1
  Pre = "home"
[[Menu.Main]]
  Name = "IT/技术"
  Pre = "code"
  URL = "/categories/IT/"
  Weight = 3
[[Menu.Main]]
  Name = "Laws/法务"
  Pre = "legal"
  URL = "/categories/Laws/"
  Weight = 5
[[Menu.Main]]
  Name = "Life/生活"
  Pre = "coffee"
  URL = "/categories/Life/"
  Weight = 7
[[Menu.Main]]
  Name = "Notes/笔记"
  Pre = "pencil-square-o"
  URL = "/categories/Notes/"
  Weight = 9
[[Menu.Main]]
  Name = "Archives/归档"
  Pre = "tasks"
  URL = "/post/"
  Weight = 11
[[Menu.Main]]
  Name = "AboutMe/关于我"
  Pre = "user"
  URL = "/about/"
  Weight = 13

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/choicky/"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/choicky-zhou"  